### ISSUE TITLE
Cannot compile with Ethernet2 library

### ISSUE THREAD

**Issue by mentaluproar** [TrippyLighting/EthernetBonjour#5]
We W5500 users need ethernet2, and it seems the changes needed to make this work do not work with the ethernet2 library.  The closest I can get is throwing ethernet2 files in the ethernet library folder, but then I get errors about redefining things.

please help

**Comment by TrippyLighting** [comment]
What errors are you getting and what Arduino IDE version are you working with ?
The EthernetBonjour library works exclusicvely with UDP calls and is not hardware dependent so should actually work with the W5500. However, I am thinking that you may be missing a couple of modifications to the EthernetUDP.cpp and .h that enable multicast DNS which is a requirement for Bonjour to work.

**Comment by TrippyLighting** [comment]
And please provide a link to the library you are mentioning.

**Comment by mentaluproar** [comment]
The ethernet2 library is included with the arduino IDE from arduino.org, not arduino.cc.

I replaced the ethernet2 library with originals and tried to modify them again.  Now, they don't work.  Sorry, I'm a noob here and while the answer is probably obvious, I cannot find it.

The changes I'm making are the ones shown here: http://forum.arduino.cc/index.php?topic=234340.0

**Comment by TrippyLighting** [comment]
If you've made the modifications to the Ethernet library (Ethernet2 in your case) I described in the post on the Arduino forum you liked to in you last post, did you replace the one reference to W5100 with W5500 ?
This may be all it takes.

**Comment by mentaluproar** [comment]
nope.  Ethernet2 doesn't work at all now.

Arduino: 1.7.7 (Mac OS X), Board: "Arduino Uno"

/Applications/Arduino.app/Contents/Java/libraries/Ethernet2/src/EthernetUdp2.cpp: In member function 'virtual uint8_t EthernetUDP::beginMulti(IPAddress, uint16_t)':
/Applications/Arduino.app/Contents/Java/libraries/Ethernet2/src/EthernetUdp2.cpp:227:16: error: 'W5500' was not declared in this scope
    uint8_t s = W5500.readSnSR(i);
                ^
/Applications/Arduino.app/Contents/Java/libraries/Ethernet2/src/EthernetUdp2.cpp:245:2: error: 'W5500' was not declared in this scope
  W5500.writeSnDIPR(_sock, rawIPAddress(ip));
  ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.


it said the same thing before, just W5100.

**Comment by mentaluproar** [comment]
Would you like me to send you the library after I made the edits?

**Comment by TrippyLighting** [comment]
@mentaluproar
Did you ever get this to work ? I have some time over the holidays to look at this and possibly finally update this library.

**Comment by mentaluproar** [comment]
I never did get it to work. I got a few other boards with Ethernet to try but haven't had time to really test them yet. I now have the arduino ethernet, arduino yun, Intel Galileo 2,  arduino uno and mega with that w5500 Ethernet shield. 

So I can certainly test whatever you want me to.

**Comment by mentaluproar** [comment]
My semester is finally over and I'm ready to test whatever code you have for me.

**Comment by GertjanBiasino** [comment]
Hi,
I have the same problem. I have an ethernet shield 2 and have to use the ethernet2 library.
When i use the oscuino library it seems to work with just replacing "include ethernet..." With ethernet2
But he oscuino library is not campatible with the other software i want to use (isadora)
To comunicate with isadora i have to use the ardosc library but then i got the same problem as you discribed above.
Also tryed to replace the files and tried to change the library files to ethernet2 and w5500 but same error as you.

Did you find a sollution?

**Comment by TrippyLighting** [comment]
You almost certainly don NOT have the same problem. As such please respect the GitHub etiquette. this is not an open discussion forum for Osucino but for the Ethernet Bonjour library.

As to you your statement that Oscuino is incompatible with Isadora, that is unlikely to be the case. What is more likely the case is that you simply have not figured out how to use Oscuino library. I'd be interested in helping you and others. A quick Google search shows that you've presented this problem on the Isadora Forum and another user advised you to use ArdOsc.
That is not good advise!
ArdOsc is very old and not maintained anymore. I switched from ArdOsc to Oscino because Oscuino is the reference implementation by the inventors of the OSC protocol and is actively maintained. Oscine also has a GitHub repository. It is also much more complete than ArdOsc.

As to the Ethernet 2 library I'll look into that. But, again please let's discuss the isadorta related topic over to my blog and the little Oscino tutorial I published there. If we figure out how to get this done in the spirit od open source I'll publish another tutorial, with code, how to send and receive OSC messages with Isadora.
